const SET_TABTITLEITEM = 'SET_TABTITLEITEM'					//// 顶部tab
const SET_DETAILCURRENTCOMPONENT = 'SET_DETAILCURRENTCOMPONENT'  // 详情加载的组件

export default {
	SET_TABTITLEITEM,
	SET_DETAILCURRENTCOMPONENT
}