// const SET_TABTITLEITEM = 'SET_TABTITLEITEM'					//// 顶部tab
// const SET_DETAILCURRENTCOMPONENT = 'SET_DETAILCURRENTCOMPONENT'  // 详情加载的组件
const SET_COURSECOLUMNS = 'SET_COURSECOLUMNS'
const SET_COURSEDATA = 'SET_COURSEDATA'
const SET_STUDENTCOLUMNS = 'SET_STUDENTCOLUMNS'
const SET_STUDENTDATA = 'SET_STUDENTDATA'
const SET_RELDEMANDANDCOURSECOLUMNS = 'SET_RELDEMANDANDCOURSECOLUMNS'
const SET_RELDEMANDANDCOURSEDATA = 'SET_RELDEMANDANDCOURSEDATA'
const SET_CURRENTUSER = 'SET_CURRENTUSER' // 当前登录用户信息
const SET_HASCOMPLETEPAGE = 'SET_HASCOMPLETEPAGE' // 已经加载完页面
const SET_DEMANDCOLUMNS = 'SET_DEMANDCOLUMNS'  // 毕业要求指标模板数据
const SET_DEMANDDATA = 'SET_DEMANDDATA'				// 毕业要求指标模板列
export default {
	// SET_TABTITLEITEM,
	// SET_DETAILCURRENTCOMPONENT,
	SET_COURSECOLUMNS,
	SET_COURSEDATA,
	SET_STUDENTCOLUMNS,
	SET_STUDENTDATA,
	SET_RELDEMANDANDCOURSECOLUMNS,
	SET_RELDEMANDANDCOURSEDATA,
	SET_CURRENTUSER,
	SET_HASCOMPLETEPAGE,
	SET_DEMANDCOLUMNS,
	SET_DEMANDDATA
}