const SET_TABTITLEITEM = 'SET_TABTITLEITEM'					//// 顶部tab
const SET_DETAILCURRENTCOMPONENT = 'SET_DETAILCURRENTCOMPONENT'  // 详情加载的组件
const SET_COURSECOLUMNS = 'SET_COURSECOLUMNS'
const SET_COURSEDATA = 'SET_COURSEDATA'
const SET_STUDENTCOLUMNS = 'SET_STUDENTCOLUMNS'
const SET_STUDENTDATA = 'SET_STUDENTDATA'
const SET_RELDEMANDANDCOURSECOLUMNS = 'SET_RELDEMANDANDCOURSECOLUMNS'
const SET_RELDEMANDANDCOURSEDATA = 'SET_RELDEMANDANDCOURSEDATA'
export default {
	SET_TABTITLEITEM,
	SET_DETAILCURRENTCOMPONENT,
	SET_COURSECOLUMNS,
	SET_COURSEDATA,
	SET_STUDENTCOLUMNS,
	SET_STUDENTDATA,
	SET_RELDEMANDANDCOURSECOLUMNS,
	SET_RELDEMANDANDCOURSEDATA
}