const SET_COURSELIST = 'SET_COURSELIST';    // 课程列表
const SET_COURSEGRADESECTION = 'SET_COURSEGRADESECTION';   	// 课程分段
const SET_COURSEAVERAGE = 'SET_COURSEAVERAGE';	// 课程平均分
const SET_COURSENAME = 'SET_COURSENAME';				// 课程名称
const SET_OVERAVGSTUINFO = 'SET_OVERAVGSTUINFO' // 达到课程平均分的人数

export default {
	SET_COURSELIST,
	SET_COURSEGRADESECTION,
	SET_COURSEAVERAGE,
	SET_COURSENAME,
	SET_OVERAVGSTUINFO
}